// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	app "power-admin-server/internal/handler/app"
	auth "power-admin-server/internal/handler/auth"
	cms "power-admin-server/internal/handler/cms"
	codegen "power-admin-server/internal/handler/codegen"
	dicts "power-admin-server/internal/handler/dicts"
	iface "power-admin-server/internal/handler/iface"
	menu "power-admin-server/internal/handler/menu"
	permissions "power-admin-server/internal/handler/permissions"
	role "power-admin-server/internal/handler/role"
	user "power-admin-server/internal/handler/user"
	"power-admin-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/app-market/install",
					Handler: app.AppInstallHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/install-status",
					Handler: app.AppInstallStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/list",
					Handler: app.AppListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/search",
					Handler: app.SearchAppHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/app-market/uninstall",
					Handler: app.AppUninstallHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/info",
					Handler: auth.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					// 创建分类
					Method:  http.MethodPost,
					Path:    "/category",
					Handler: cms.CategoryCreateHandler(serverCtx),
				},
				{
					// 更新分类
					Method:  http.MethodPut,
					Path:    "/category/:id",
					Handler: cms.CategoryUpdateHandler(serverCtx),
				},
				{
					// 删除分类
					Method:  http.MethodDelete,
					Path:    "/category/:id",
					Handler: cms.CategoryDeleteHandler(serverCtx),
				},
				{
					// 获取分类列表
					Method:  http.MethodGet,
					Path:    "/category/list",
					Handler: cms.CategoryListHandler(serverCtx),
				},
				{
					// 获取分类树
					Method:  http.MethodGet,
					Path:    "/category/tree",
					Handler: cms.CategoryTreeHandler(serverCtx),
				},
				{
					// 删除评论
					Method:  http.MethodDelete,
					Path:    "/comment/:id",
					Handler: cms.CommentDeleteHandler(serverCtx),
				},
				{
					// 审核评论
					Method:  http.MethodPost,
					Path:    "/comment/:id/approve",
					Handler: cms.CommentApproveHandler(serverCtx),
				},
				{
					// 拒绝评论
					Method:  http.MethodPost,
					Path:    "/comment/:id/reject",
					Handler: cms.CommentRejectHandler(serverCtx),
				},
				{
					// 获取评论列表
					Method:  http.MethodGet,
					Path:    "/comment/list",
					Handler: cms.CommentListHandler(serverCtx),
				},
				{
					// 创建内容
					Method:  http.MethodPost,
					Path:    "/content",
					Handler: cms.ContentCreateHandler(serverCtx),
				},
				{
					// 获取内容详情
					Method:  http.MethodGet,
					Path:    "/content/:id",
					Handler: cms.ContentGetHandler(serverCtx),
				},
				{
					// 更新内容
					Method:  http.MethodPut,
					Path:    "/content/:id",
					Handler: cms.ContentUpdateHandler(serverCtx),
				},
				{
					// 删除内容
					Method:  http.MethodDelete,
					Path:    "/content/:id",
					Handler: cms.ContentDeleteHandler(serverCtx),
				},
				{
					// 发布内容
					Method:  http.MethodPost,
					Path:    "/content/:id/publish",
					Handler: cms.ContentPublishHandler(serverCtx),
				},
				{
					// 取消发布
					Method:  http.MethodPost,
					Path:    "/content/:id/unpublish",
					Handler: cms.ContentUnpublishHandler(serverCtx),
				},
				{
					// 获取内容列表
					Method:  http.MethodGet,
					Path:    "/content/list",
					Handler: cms.ContentListHandler(serverCtx),
				},
				{
					// 批量发布
					Method:  http.MethodPost,
					Path:    "/publish/batch",
					Handler: cms.PublishBatchHandler(serverCtx),
				},
				{
					// 取消定时发布
					Method:  http.MethodPost,
					Path:    "/publish/cancel/:id",
					Handler: cms.PublishCancelHandler(serverCtx),
				},
				{
					// 立即发布
					Method:  http.MethodPost,
					Path:    "/publish/immediate",
					Handler: cms.PublishImmediateHandler(serverCtx),
				},
				{
					// 定时发布
					Method:  http.MethodPost,
					Path:    "/publish/schedule",
					Handler: cms.PublishScheduleHandler(serverCtx),
				},
				{
					// 创建标签
					Method:  http.MethodPost,
					Path:    "/tag",
					Handler: cms.TagCreateHandler(serverCtx),
				},
				{
					// 更新标签
					Method:  http.MethodPut,
					Path:    "/tag/:id",
					Handler: cms.TagUpdateHandler(serverCtx),
				},
				{
					// 删除标签
					Method:  http.MethodDelete,
					Path:    "/tag/:id",
					Handler: cms.TagDeleteHandler(serverCtx),
				},
				{
					// 获取标签列表
					Method:  http.MethodGet,
					Path:    "/tag/list",
					Handler: cms.TagListHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: cms.UserGetHandler(serverCtx),
				},
				{
					// 禁用用户
					Method:  http.MethodPost,
					Path:    "/user/:id/disable",
					Handler: cms.UserDisableHandler(serverCtx),
				},
				{
					// 启用用户
					Method:  http.MethodPost,
					Path:    "/user/:id/enable",
					Handler: cms.UserEnableHandler(serverCtx),
				},
				{
					// 获取用户列表
					Method:  http.MethodGet,
					Path:    "/user/list",
					Handler: cms.UserListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/cms"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/config",
					Handler: codegen.CreateConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/config/:id",
					Handler: codegen.UpdateConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/config/:id",
					Handler: codegen.DeleteConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/config/:id",
					Handler: codegen.GetConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/config/list",
					Handler: codegen.ListConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/database/tables",
					Handler: codegen.GetDatabaseTablesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/generate",
					Handler: codegen.GenerateCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/history/:id",
					Handler: codegen.GetHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/history/:id",
					Handler: codegen.DeleteHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/history/list",
					Handler: codegen.ListHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import/table",
					Handler: codegen.ImportTableHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/preview",
					Handler: codegen.PreviewCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/codegen"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/content/dicts",
					Handler: dicts.DictListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/content/dicts",
					Handler: dicts.CreateDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/content/dicts",
					Handler: dicts.UpdateDictHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/content/dicts",
					Handler: dicts.DeleteDictHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/content/dicts/:id",
					Handler: dicts.GetDictHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/apis",
					Handler: iface.ApiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/apis",
					Handler: iface.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/apis",
					Handler: iface.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/apis/:id",
					Handler: iface.UpdateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/apis/:id",
					Handler: iface.GetApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/menus",
					Handler: menu.MenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/menus",
					Handler: menu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/menus",
					Handler: menu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/menus",
					Handler: menu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/menus/:id",
					Handler: menu.GetMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/permissions",
					Handler: permissions.PermissionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/permissions",
					Handler: permissions.CreatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/permissions",
					Handler: permissions.UpdatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/permissions",
					Handler: permissions.DeletePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/permissions/:id",
					Handler: permissions.GetPermissionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/roles",
					Handler: role.RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles",
					Handler: role.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/roles",
					Handler: role.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/roles",
					Handler: role.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id",
					Handler: role.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id/menu-and-api",
					Handler: role.GetRoleMenuAndApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles/:id/menu-and-api",
					Handler: role.AssignRoleMenuAndApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id/permissions",
					Handler: role.GetRolePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles/:id/permissions",
					Handler: role.AssignPermissionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/users",
					Handler: user.UserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/users",
					Handler: user.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/users",
					Handler: user.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/users",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/users/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/users/:id/roles",
					Handler: user.GetUserRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/users/:id/roles",
					Handler: user.AssignRolesToUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)
}
