// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	app "power-admin-server/internal/handler/app"
	auth "power-admin-server/internal/handler/auth"
	dicts "power-admin-server/internal/handler/dicts"
	iface "power-admin-server/internal/handler/iface"
	menu "power-admin-server/internal/handler/menu"
	permissions "power-admin-server/internal/handler/permissions"
	role "power-admin-server/internal/handler/role"
	user "power-admin-server/internal/handler/user"
	"power-admin-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/app-market/install",
					Handler: app.AppInstallHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/install-status",
					Handler: app.AppInstallStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/list",
					Handler: app.AppListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/app-market/search",
					Handler: app.SearchAppHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/app-market/uninstall",
					Handler: app.AppUninstallHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/info",
					Handler: auth.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/content/dicts",
					Handler: dicts.DictListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/content/dicts",
					Handler: dicts.CreateDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/content/dicts",
					Handler: dicts.UpdateDictHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/content/dicts",
					Handler: dicts.DeleteDictHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/content/dicts/:id",
					Handler: dicts.GetDictHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/apis",
					Handler: iface.ApiListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/apis",
					Handler: iface.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/apis",
					Handler: iface.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/apis/:id",
					Handler: iface.UpdateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/apis/:id",
					Handler: iface.GetApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/menus",
					Handler: menu.MenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/menus",
					Handler: menu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/menus",
					Handler: menu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/menus",
					Handler: menu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/menus/:id",
					Handler: menu.GetMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/permissions",
					Handler: permissions.PermissionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/permissions",
					Handler: permissions.CreatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/permissions",
					Handler: permissions.UpdatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/permissions",
					Handler: permissions.DeletePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/permissions/:id",
					Handler: permissions.GetPermissionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/roles",
					Handler: role.RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles",
					Handler: role.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/roles",
					Handler: role.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/roles",
					Handler: role.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id",
					Handler: role.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id/menu-and-api",
					Handler: role.GetRoleMenuAndApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles/:id/menu-and-api",
					Handler: role.AssignRoleMenuAndApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/roles/:id/permissions",
					Handler: role.GetRolePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/roles/:id/permissions",
					Handler: role.AssignPermissionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/users",
					Handler: user.UserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/users",
					Handler: user.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/system/users",
					Handler: user.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/system/users",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/users/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/system/users/:id/roles",
					Handler: user.GetUserRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/system/users/:id/roles",
					Handler: user.AssignRolesToUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)
}
