// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiInfo struct {
	Id          int64  `json:"id"`
	ApiName     string `json:"apiName"`
	ApiPath     string `json:"apiPath"`
	ApiMethod   string `json:"apiMethod"`
	Group       string `json:"group"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type ApiListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	ApiPath  string `form:"apiPath,optional"`
}

type ApiListResp struct {
	Total    int64     `json:"total"`
	ApiInfos []ApiInfo `json:"list"`
}

type AppInfo struct {
	Id          int64   `json:"id"`
	AppKey      string  `json:"appKey"`
	AppName     string  `json:"appName"`
	Version     string  `json:"version"`
	Author      string  `json:"author"`
	Description string  `json:"description"`
	Icon        string  `json:"icon"`
	DownloadUrl string  `json:"downloadUrl"`
	DemoUrl     string  `json:"demoUrl"`
	Category    string  `json:"category"`
	Tags        string  `json:"tags"`
	Rating      float64 `json:"rating"`
	Downloads   int64   `json:"downloads"`
	Status      int     `json:"status"`
	Published   int     `json:"published"`
	Installed   bool    `json:"installed"`
	CreatedAt   string  `json:"createdAt"`
}

type AppInstallReq struct {
	AppId  int64  `form:"appId"`
	AppKey string `form:"appKey"`
}

type AppInstallResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AppInstallStatusReq struct {
	AppKey string `form:"appKey"`
}

type AppInstallStatusResp struct {
	AppKey    string `json:"appKey"`
	Installed bool   `json:"installed"`
}

type AppListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Category string `form:"category,optional"`
}

type AppListResp struct {
	Total int64     `json:"total"`
	List  []AppInfo `json:"list"`
}

type AppUninstallReq struct {
	AppKey string `form:"appKey"`
}

type AppUninstallResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignPermissionsReq struct {
	RoleID        int64   `json:"roleId" path:"id"`
	PermissionIds []int64 `json:"permissionIds"`
}

type AssignPermissionsResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignRoleMenuAndApiReq struct {
	RoleId  int64   `json:"roleId" path:"id"`
	MenuIds []int64 `json:"menuIds"`
	ApiIds  []int64 `json:"apiIds"`
}

type AssignRoleMenuAndApiResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignRolesToUserReq struct {
	UserID  int64   `json:"userId" path:"id"`
	RoleIds []int64 `json:"roleIds"`
}

type AssignRolesToUserResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateApiReq struct {
	ApiName     string `json:"apiName"`
	ApiPath     string `json:"apiPath"`
	ApiMethod   string `json:"apiMethod"`
	Description string `json:"description,optional"`
}

type CreateDictReq struct {
	Dict        string `json:"dict"`
	DictLabel   string `json:"dictLabel"`
	DictValue   string `json:"dictValue"`
	Description string `json:"description,optional"`
	DictType    string `json:"dictType,optional"`
	Sort        int    `json:"sort,default=0"`
}

type CreateMenuReq struct {
	ParentId  int64  `json:"parentId,optional"`
	MenuName  string `json:"menuName"`
	MenuPath  string `json:"menuPath,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int    `json:"sort,default=0"`
	Menu      int    `json:"menu,default=1"`
	MenuType  int    `json:"menuType,default=1"`
}

type CreatePermissionReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
}

type CreateRoleReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	Nickname string `json:"nickname,optional"`
	Gender   int    `json:"gender,default=0"`
	Password string `json:"password"`
}

type DeleteApiReq struct {
	Id int64 `json:"id"`
}

type DeleteDictReq struct {
	Id int64 `json:"id"`
}

type DeleteMenuReq struct {
	Id int64 `json:"id"`
}

type DeletePermissionReq struct {
	Id int64 `json:"id"`
}

type DeleteRoleReq struct {
	Id int64 `json:"id"`
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DictInfo struct {
	Id          int64  `json:"id"`
	Dict        string `json:"dict"`
	DictLabel   string `json:"dictLabel"`
	DictValue   string `json:"dictValue"`
	Description string `json:"description"`
	Sort        int    `json:"sort"`
	DictType    string `json:"dictType"`
	Status      int    `json:"status"`
}

type DictListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Dict     string `form:"dict,optional"`
}

type DictListResp struct {
	Total int64      `json:"total"`
	Data  []DictInfo `json:"list"`
}

type GetApiReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetDictReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetMenuReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetPermissionReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetRoleMenuAndApiResp struct {
	Menus           []RolePermissionItem `json:"menus"`
	Apis            []RolePermissionItem `json:"apis"`
	SelectedMenuIds []int64              `json:"selectedMenuIds"`
	SelectedApiIds  []int64              `json:"selectedApiIds"`
}

type GetRolePermissionsReq struct {
	RoleID int64 `json:"roleId,optional" path:"id"`
}

type GetRolePermissionsResp struct {
	Data []PermissionInfo `json:"data"`
}

type GetRoleReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetUserReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetUserRolesReq struct {
	UserID int64 `json:"userId,optional" path:"id"`
}

type GetUserRolesResp struct {
	Data []RoleInfo `json:"data"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type MenuItem struct {
	Id        int64      `json:"id"`
	ParentId  int64      `json:"parentId"`
	MenuName  string     `json:"menuName"`
	MenuPath  string     `json:"menuPath"`
	Component string     `json:"component"`
	Icon      string     `json:"icon"`
	Sort      int        `json:"sort"`
	Status    int        `json:"status"`
	Menu      int        `json:"menu"`
	MenuType  int        `json:"menuType"`
	CreatedAt string     `json:"createdAt"`
	Children  []MenuItem `json:"children,optional"`
}

type MenuListReq struct {
	Page     int   `json:"page,default=1"`
	PageSize int   `json:"pageSize,default=10"`
	ParentId int64 `json:"parentId,optional"`
}

type MenuListResp struct {
	Total int64      `json:"total"`
	Data  []MenuItem `json:"list"`
}

type PermissionInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type PermissionListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Resource string `json:"resource,optional"`
}

type PermissionListResp struct {
	Total int64            `json:"total"`
	Data  []PermissionInfo `json:"list"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type RoleInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type RoleListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Name     string `json:"name,optional"`
}

type RoleListResp struct {
	Total int64      `json:"total"`
	Data  []RoleInfo `json:"list"`
}

type RolePermissionItem struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId,optional"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	Type     string `json:"type"`            // "menu" 或 "api"
	Group    string `json:"group,optional"`  // API所属分组
	Method   string `json:"method,optional"` // API的HTTP方法
}

type UpdateApiReq struct {
	Id     int64 `json:"id" path:"id"`
	Status int   `json:"status,optional"`
}

type UpdateDictReq struct {
	Id        int64  `json:"id"`
	DictLabel string `json:"dictLabel,optional"`
	Sort      int    `json:"sort,optional"`
	Status    int    `json:"status,optional"`
}

type UpdateMenuReq struct {
	Id        int64  `json:"id"`
	MenuName  string `json:"menuName,optional"`
	MenuPath  string `json:"menuPath,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int    `json:"sort,optional"`
	Status    int    `json:"status,optional"`
	Menu      int    `json:"menu,optional"`
	MenuType  int    `json:"menuType,optional"`
}

type UpdatePermissionReq struct {
	Id     int64 `json:"id"`
	Status int   `json:"status,optional"`
}

type UpdateRoleReq struct {
	Id          int64  `json:"id"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email,optional"`
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Gender   int    `json:"gender,optional"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Gender    int    `json:"gender"`
	Status    int    `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
}

type UserListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Username string `json:"username,optional"`
	Phone    string `json:"phone,optional"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	Data  []UserInfo `json:"list"`
}
