// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiInfo struct {
	Id          int64  `json:"id"`
	ApiName     string `json:"apiName"`
	ApiPath     string `json:"apiPath"`
	ApiMethod   string `json:"apiMethod"`
	Group       string `json:"group"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type ApiListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	ApiPath  string `form:"apiPath,optional"`
}

type ApiListResp struct {
	Total    int64     `json:"total"`
	ApiInfos []ApiInfo `json:"list"`
}

type AppInfo struct {
	Id          int64   `json:"id"`
	AppKey      string  `json:"appKey"`
	AppName     string  `json:"appName"`
	Version     string  `json:"version"`
	Author      string  `json:"author"`
	Description string  `json:"description"`
	Icon        string  `json:"icon"`
	DownloadUrl string  `json:"downloadUrl"`
	DemoUrl     string  `json:"demoUrl"`
	Category    string  `json:"category"`
	Tags        string  `json:"tags"`
	Rating      float64 `json:"rating"`
	Downloads   int64   `json:"downloads"`
	Status      int     `json:"status"`
	Published   int     `json:"published"`
	Installed   bool    `json:"installed"`
	CreatedAt   string  `json:"createdAt"`
}

type AppInstallReq struct {
	AppId  int64  `form:"appId"`
	AppKey string `form:"appKey"`
}

type AppInstallResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AppInstallStatusReq struct {
	AppKey string `form:"appKey"`
}

type AppInstallStatusResp struct {
	AppKey    string `json:"appKey"`
	Installed bool   `json:"installed"`
}

type AppListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Category string `form:"category,optional"`
}

type AppListResp struct {
	Total int64     `json:"total"`
	List  []AppInfo `json:"list"`
}

type AppUninstallReq struct {
	AppKey string `form:"appKey"`
}

type AppUninstallResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignPermissionsReq struct {
	RoleID        int64   `json:"roleId" path:"id"`
	PermissionIds []int64 `json:"permissionIds"`
}

type AssignPermissionsResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignRoleMenuAndApiReq struct {
	RoleId  int64   `json:"roleId" path:"id"`
	MenuIds []int64 `json:"menuIds"`
	ApiIds  []int64 `json:"apiIds"`
}

type AssignRoleMenuAndApiResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AssignRolesToUserReq struct {
	UserID  int64   `json:"userId" path:"id"`
	RoleIds []int64 `json:"roleIds"`
}

type AssignRolesToUserResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CategoryCreateReq struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	ParentId    int64  `json:"parentId"`
}

type CategoryData struct {
	Id          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	ParentId    int64          `json:"parentId"`
	Children    []CategoryData `json:"children,omitempty"`
}

type CategoryDeleteReq struct {
	Id int64 `json:"id" path:"id"`
}

type CategoryListReq struct {
	ParentId int64 `json:"parentId"`
}

type CategoryListResp struct {
	Total int64          `json:"total"`
	Data  []CategoryData `json:"data"`
}

type CategoryResp struct {
	Data []CategoryData `json:"data"`
}

type CategoryUpdateReq struct {
	Id          int64  `json:"id" path:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	ParentId    int64  `json:"parentId"`
}

type CmsUserListReq struct {
	Page     int `json:"page,default=1"`
	PageSize int `json:"pageSize,default=10"`
}

type CmsUserListResp struct {
	Total int64      `json:"total"`
	Data  []UserData `json:"data"`
}

type CodeGenerateReq struct {
	ID int64 `json:"id"`
}

type CodeGenerateResp struct {
	Success   bool             `json:"success"`
	Message   string           `json:"message"`
	Files     []GeneratedFile  `json:"files,omitempty"`
	Histories []GenHistoryResp `json:"histories,omitempty"`
}

type CodePreviewReq struct {
	ID int64 `json:"id"`
}

type CodePreviewResp struct {
	Files []GeneratedFile `json:"files"`
}

type ColumnInfo struct {
	ColumnName    string `json:"columnName"`
	ColumnType    string `json:"columnType"`
	DataType      string `json:"dataType"`
	ColumnComment string `json:"columnComment"`
	IsNullable    string `json:"isNullable"`
	ColumnKey     string `json:"columnKey"`
	Extra         string `json:"extra"`
}

type CommentApproveReq struct {
	Id int64 `json:"id" path:"id"`
}

type CommentCreateReq struct {
	ContentId   string `json:"contentId"`
	Content     string `json:"content"`
	AuthorName  string `json:"authorName"`
	AuthorEmail string `json:"authorEmail"`
}

type CommentData struct {
	Id      int64  `json:"id"`
	Content string `json:"content"`
	Status  int    `json:"status"`
}

type CommentDeleteReq struct {
	Id int64 `json:"id" path:"id"`
}

type CommentListReq struct {
	ContentId int64 `json:"contentId"`
	Page      int   `json:"page,default=1"`
	PageSize  int   `json:"pageSize,default=10"`
}

type CommentListResp struct {
	Total int64         `json:"total"`
	Data  []CommentData `json:"data"`
}

type CommentRejectReq struct {
	Id int64 `json:"id" path:"id"`
}

type ContentCreateReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Slug        string `json:"slug"`
	CategoryId  int64  `json:"categoryId"`
	Status      int    `json:"status,default=1"`
}

type ContentData struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Content      string `json:"content"`
	Slug         string `json:"slug"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	Status       int    `json:"status"`
	ViewCount    int64  `json:"viewCount"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type ContentListReq struct {
	Page       int    `json:"page,default=1"`
	PageSize   int    `json:"pageSize,default=10"`
	Status     int    `json:"status"`
	CategoryId int64  `json:"categoryId"`
	Search     string `json:"search"`
}

type ContentListResp struct {
	Total int64         `json:"total"`
	Data  []ContentData `json:"data"`
}

type ContentResp struct {
	Data ContentData `json:"data"`
}

type ContentUpdateReq struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Slug        string `json:"slug"`
	CategoryId  int64  `json:"categoryId"`
	Status      int    `json:"status"`
}

type CreateApiReq struct {
	ApiName     string `json:"apiName"`
	ApiPath     string `json:"apiPath"`
	ApiMethod   string `json:"apiMethod"`
	Description string `json:"description,optional"`
}

type CreateDictReq struct {
	Dict        string `json:"dict"`
	DictLabel   string `json:"dictLabel"`
	DictValue   string `json:"dictValue"`
	Description string `json:"description,optional"`
	DictType    string `json:"dictType,optional"`
	Sort        int    `json:"sort,default=0"`
}

type CreateMenuReq struct {
	ParentId  int64  `json:"parentId,optional"`
	MenuName  string `json:"menuName"`
	MenuPath  string `json:"menuPath,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int    `json:"sort,default=0"`
	Menu      int    `json:"menu,default=1"`
	MenuType  int    `json:"menuType,default=1"`
}

type CreatePermissionReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
}

type CreateRoleReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	Nickname string `json:"nickname,optional"`
	Gender   int    `json:"gender,default=0"`
	Password string `json:"password"`
}

type DatabaseTableInfo struct {
	TableName    string       `json:"tableName"`
	TableComment string       `json:"tableComment"`
	Engine       string       `json:"engine"`
	Charset      string       `json:"charset"`
	Columns      []ColumnInfo `json:"columns"`
}

type DeleteApiReq struct {
	Id int64 `json:"id"`
}

type DeleteDictReq struct {
	Id int64 `json:"id"`
}

type DeleteMenuReq struct {
	Id int64 `json:"id"`
}

type DeletePermissionReq struct {
	Id int64 `json:"id"`
}

type DeleteRoleReq struct {
	Id int64 `json:"id"`
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DictInfo struct {
	Id          int64  `json:"id"`
	Dict        string `json:"dict"`
	DictLabel   string `json:"dictLabel"`
	DictValue   string `json:"dictValue"`
	Description string `json:"description"`
	Sort        int    `json:"sort"`
	DictType    string `json:"dictType"`
	Status      int    `json:"status"`
}

type DictListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Dict     string `form:"dict,optional"`
}

type DictListResp struct {
	Total int64      `json:"total"`
	Data  []DictInfo `json:"list"`
}

type GenConfigListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	TableName string `form:"tableName,optional"`
}

type GenConfigListResp struct {
	Total int64           `json:"total"`
	Data  []GenConfigResp `json:"data"`
}

type GenConfigReq struct {
	TableName    string              `json:"tableName"`
	TablePrefix  string              `json:"tablePrefix,optional"`
	BusinessName string              `json:"businessName"`
	ModuleName   string              `json:"moduleName"`
	PackageName  string              `json:"packageName"`
	Author       string              `json:"author,optional"`
	Remark       string              `json:"remark,optional"`
	Columns      []GenTableColumnReq `json:"columns"`
}

type GenConfigResp struct {
	ID           int64                `json:"id"`
	TableName    string               `json:"tableName"`
	TablePrefix  string               `json:"tablePrefix"`
	BusinessName string               `json:"businessName"`
	ModuleName   string               `json:"moduleName"`
	PackageName  string               `json:"packageName"`
	Author       string               `json:"author"`
	Remark       string               `json:"remark"`
	CreatedAt    string               `json:"createdAt"`
	UpdatedAt    string               `json:"updatedAt"`
	Columns      []GenTableColumnResp `json:"columns,omitempty"`
}

type GenHistoryListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	TableName string `form:"tableName,optional"`
}

type GenHistoryListResp struct {
	Total int64            `json:"total"`
	Data  []GenHistoryResp `json:"data"`
}

type GenHistoryResp struct {
	ID          int64  `json:"id"`
	GenConfigID int64  `json:"genConfigId"`
	TableName   string `json:"tableName"`
	FilePath    string `json:"filePath"`
	FileType    string `json:"fileType"`
	Content     string `json:"content"`
	Status      int    `json:"status"`
	ErrorMsg    string `json:"errorMsg"`
	Operator    string `json:"operator"`
	CreatedAt   string `json:"createdAt"`
}

type GenTableColumnReq struct {
	ColumnName    string `json:"columnName"`
	ColumnComment string `json:"columnComment,optional"`
	ColumnType    string `json:"columnType"`
	GoType        string `json:"goType"`
	GoField       string `json:"goField"`
	IsPk          int    `json:"isPk,optional"`
	IsIncrement   int    `json:"isIncrement,optional"`
	IsRequired    int    `json:"isRequired,optional"`
	IsInsert      int    `json:"isInsert,optional"`
	IsEdit        int    `json:"isEdit,optional"`
	IsList        int    `json:"isList,optional"`
	IsQuery       int    `json:"isQuery,optional"`
	QueryType     string `json:"queryType,optional"`
	HtmlType      string `json:"htmlType,optional"`
	DictType      string `json:"dictType,optional"`
	Sort          int    `json:"sort,optional"`
}

type GenTableColumnResp struct {
	ID            int64  `json:"id"`
	GenConfigID   int64  `json:"genConfigId"`
	ColumnName    string `json:"columnName"`
	ColumnComment string `json:"columnComment"`
	ColumnType    string `json:"columnType"`
	GoType        string `json:"goType"`
	GoField       string `json:"goField"`
	IsPk          int    `json:"isPk"`
	IsIncrement   int    `json:"isIncrement"`
	IsRequired    int    `json:"isRequired"`
	IsInsert      int    `json:"isInsert"`
	IsEdit        int    `json:"isEdit"`
	IsList        int    `json:"isList"`
	IsQuery       int    `json:"isQuery"`
	QueryType     string `json:"queryType"`
	HtmlType      string `json:"htmlType"`
	DictType      string `json:"dictType"`
	Sort          int    `json:"sort"`
}

type GeneratedFile struct {
	FilePath string `json:"filePath"`
	FileType string `json:"fileType"`
	Content  string `json:"content"`
}

type GetApiReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetDatabaseTablesReq struct {
	TableName string `form:"tableName,optional"`
}

type GetDatabaseTablesResp struct {
	Tables []DatabaseTableInfo `json:"tables"`
}

type GetDictReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetHistoryReq struct {
	Id int64 `path:"id"`
}

type GetMenuReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetPermissionReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetRoleMenuAndApiResp struct {
	Menus           []RolePermissionItem `json:"menus"`
	Apis            []RolePermissionItem `json:"apis"`
	SelectedMenuIds []int64              `json:"selectedMenuIds"`
	SelectedApiIds  []int64              `json:"selectedApiIds"`
}

type GetRolePermissionsReq struct {
	RoleID int64 `json:"roleId,optional" path:"id"`
}

type GetRolePermissionsResp struct {
	Data []PermissionInfo `json:"data"`
}

type GetRoleReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetUserReq struct {
	Id int64 `json:"id" path:"id"`
}

type GetUserRolesReq struct {
	UserID int64 `json:"userId,optional" path:"id"`
}

type GetUserRolesResp struct {
	Data []RoleInfo `json:"data"`
}

type IdReq struct {
	Id int64 `json:"id" path:"id"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type MenuItem struct {
	Id        int64      `json:"id"`
	ParentId  int64      `json:"parentId"`
	MenuName  string     `json:"menuName"`
	MenuPath  string     `json:"menuPath"`
	Component string     `json:"component"`
	Icon      string     `json:"icon"`
	Sort      int        `json:"sort"`
	Status    int        `json:"status"`
	Menu      int        `json:"menu"`
	MenuType  int        `json:"menuType"`
	CreatedAt string     `json:"createdAt"`
	Children  []MenuItem `json:"children,optional"`
}

type MenuListReq struct {
	Page     int   `json:"page,default=1"`
	PageSize int   `json:"pageSize,default=10"`
	ParentId int64 `json:"parentId,optional"`
}

type MenuListResp struct {
	Total int64      `json:"total"`
	Data  []MenuItem `json:"list"`
}

type PermissionInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type PermissionListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Resource string `json:"resource,optional"`
}

type PermissionListResp struct {
	Total int64            `json:"total"`
	Data  []PermissionInfo `json:"list"`
}

type PublishBatchReq struct {
	Ids []int64 `json:"ids"`
}

type PublishCancelReq struct {
	Id int64 `json:"id" path:"id"`
}

type PublishImmediateReq struct {
	Id int64 `json:"id"`
}

type PublishScheduleReq struct {
	Id         int64  `json:"id"`
	ScheduleAt string `json:"scheduleAt"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type RoleInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type RoleListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Name     string `json:"name,optional"`
}

type RoleListResp struct {
	Total int64      `json:"total"`
	Data  []RoleInfo `json:"list"`
}

type RolePermissionItem struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId,optional"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	Type     string `json:"type"`            // "menu" 或 "api"
	Group    string `json:"group,optional"`  // API所属分组
	Method   string `json:"method,optional"` // API的HTTP方法
}

type TagCreateReq struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type TagData struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type TagDeleteReq struct {
	Id int64 `json:"id" path:"id"`
}

type TagListReq struct {
	Page     int `json:"page,default=1"`
	PageSize int `json:"pageSize,default=10"`
}

type TagListResp struct {
	Total int64     `json:"total"`
	Data  []TagData `json:"data"`
}

type TagUpdateReq struct {
	Id          int64  `json:"id" path:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type UpdateApiReq struct {
	Id     int64 `json:"id" path:"id"`
	Status int   `json:"status,optional"`
}

type UpdateDictReq struct {
	Id        int64  `json:"id"`
	DictLabel string `json:"dictLabel,optional"`
	Sort      int    `json:"sort,optional"`
	Status    int    `json:"status,optional"`
}

type UpdateMenuReq struct {
	Id        int64  `json:"id"`
	MenuName  string `json:"menuName,optional"`
	MenuPath  string `json:"menuPath,optional"`
	Component string `json:"component,optional"`
	Icon      string `json:"icon,optional"`
	Sort      int    `json:"sort,optional"`
	Status    int    `json:"status,optional"`
	Menu      int    `json:"menu,optional"`
	MenuType  int    `json:"menuType,optional"`
}

type UpdatePermissionReq struct {
	Id     int64 `json:"id"`
	Status int   `json:"status,optional"`
}

type UpdateRoleReq struct {
	Id          int64  `json:"id"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email,optional"`
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Gender   int    `json:"gender,optional"`
}

type UserData struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Status    int    `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type UserDisableReq struct {
	Id int64 `json:"id" path:"id"`
}

type UserEnableReq struct {
	Id int64 `json:"id" path:"id"`
}

type UserGetReq struct {
	Id int64 `json:"id" path:"id"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Gender    int    `json:"gender"`
	Status    int    `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
}

type UserListReq struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"pageSize,default=10"`
	Username string `json:"username,optional"`
	Phone    string `json:"phone,optional"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	Data  []UserInfo `json:"list"`
}

type UserResp struct {
	Data UserData `json:"data"`
}
